version: '2'
services:
  serve:
        image: ashander/rpy:r2.3.2-py3.4.4-stretch
        working_dir: /site
        volumes:
                - .:/site
        ports:
                - "8000:8000"
        command: /bin/bash
